	

# -*- mode: ruby -*-
# vi: set ft=ruby :


types = ['master', 'infra', 'app']

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.require_version ">= 1.7.0"
Vagrant.configure("2") do |config|

  types.each do |t|
    3.times do |i|
      config.vm.define "k3s-#{t}-#{i}" do |config|
      config.vm.hostname = "k3s-#{t}-#{i}"
      config.vm.box = "ubuntu-22.04-amd64"
      #config.vm.box = "generic/ubuntu2204"
      config.vm.box_check_update = true
      config.ssh.insert_key = true
      config.vm.network "private_network", ip: "192.168.122.1#{ types.find_index(t) }#{ i }", :libvirt__network_name => 'playbooknet'
      # config.vm.provision :ansible do |ansible|
      #   ansible.verbose = "v"
      #   ansible.limit = "all"
      #   ansible.config_file = "../ansible/ansible.cfg"
      #   ansible.inventory_path = "../ansible/inventory/hosts.ini" 
      #   ansible.playbook = "../ansible/playbooks/site.yml"
      # end
      config.vm.provider :libvirt do |v|
        v.memory = 4096
        v.cpus = 5
        v.default_prefix="playbook-"
        end
      end
    end
  end
end
